package com.example.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.example.demo.domain.TryMybatisGenerator;
import com.example.demo.domain.TryMybatisGeneratorExample;

@Mapper
public interface TryMybatisGeneratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    @SelectProvider(type=TryMybatisGeneratorSqlProvider.class, method="countByExample")
    long countByExample(TryMybatisGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    @DeleteProvider(type=TryMybatisGeneratorSqlProvider.class, method="deleteByExample")
    int deleteByExample(TryMybatisGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    @Delete({
        "delete from try_mybatis_generator",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    @Insert({
        "insert into try_mybatis_generator (id, column1, ",
        "column2, column3)",
        "values (#{id,jdbcType=BIGINT}, #{column1,jdbcType=VARCHAR}, ",
        "#{column2,jdbcType=VARCHAR}, #{column3,jdbcType=VARCHAR})"
    })
    int insert(TryMybatisGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    @InsertProvider(type=TryMybatisGeneratorSqlProvider.class, method="insertSelective")
    int insertSelective(TryMybatisGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    @SelectProvider(type=TryMybatisGeneratorSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="column1", property="column1", jdbcType=JdbcType.VARCHAR),
        @Result(column="column2", property="column2", jdbcType=JdbcType.VARCHAR),
        @Result(column="column3", property="column3", jdbcType=JdbcType.VARCHAR)
    })
    List<TryMybatisGenerator> selectByExample(TryMybatisGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    @Select({
        "select",
        "id, column1, column2, column3",
        "from try_mybatis_generator",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="column1", property="column1", jdbcType=JdbcType.VARCHAR),
        @Result(column="column2", property="column2", jdbcType=JdbcType.VARCHAR),
        @Result(column="column3", property="column3", jdbcType=JdbcType.VARCHAR)
    })
    TryMybatisGenerator selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    @UpdateProvider(type=TryMybatisGeneratorSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TryMybatisGenerator record, @Param("example") TryMybatisGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    @UpdateProvider(type=TryMybatisGeneratorSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TryMybatisGenerator record, @Param("example") TryMybatisGeneratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    @UpdateProvider(type=TryMybatisGeneratorSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TryMybatisGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    @Update({
        "update try_mybatis_generator",
        "set column1 = #{column1,jdbcType=VARCHAR},",
          "column2 = #{column2,jdbcType=VARCHAR},",
          "column3 = #{column3,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TryMybatisGenerator record);
}