package com.example.demo.mapper;

import com.example.demo.domain.TryMybatisGenerator;
import com.example.demo.domain.TryMybatisGeneratorExample.Criteria;
import com.example.demo.domain.TryMybatisGeneratorExample.Criterion;
import com.example.demo.domain.TryMybatisGeneratorExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class TryMybatisGeneratorSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public String countByExample(TryMybatisGeneratorExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("try_mybatis_generator");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public String deleteByExample(TryMybatisGeneratorExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("try_mybatis_generator");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public String insertSelective(TryMybatisGenerator record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("try_mybatis_generator");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getColumn1() != null) {
            sql.VALUES("column1", "#{column1,jdbcType=VARCHAR}");
        }
        
        if (record.getColumn2() != null) {
            sql.VALUES("column2", "#{column2,jdbcType=VARCHAR}");
        }
        
        if (record.getColumn3() != null) {
            sql.VALUES("column3", "#{column3,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public String selectByExample(TryMybatisGeneratorExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("column1");
        sql.SELECT("column2");
        sql.SELECT("column3");
        sql.FROM("try_mybatis_generator");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TryMybatisGenerator record = (TryMybatisGenerator) parameter.get("record");
        TryMybatisGeneratorExample example = (TryMybatisGeneratorExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("try_mybatis_generator");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getColumn1() != null) {
            sql.SET("column1 = #{record.column1,jdbcType=VARCHAR}");
        }
        
        if (record.getColumn2() != null) {
            sql.SET("column2 = #{record.column2,jdbcType=VARCHAR}");
        }
        
        if (record.getColumn3() != null) {
            sql.SET("column3 = #{record.column3,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("try_mybatis_generator");
        
        sql.SET("id = #{record.id,jdbcType=BIGINT}");
        sql.SET("column1 = #{record.column1,jdbcType=VARCHAR}");
        sql.SET("column2 = #{record.column2,jdbcType=VARCHAR}");
        sql.SET("column3 = #{record.column3,jdbcType=VARCHAR}");
        
        TryMybatisGeneratorExample example = (TryMybatisGeneratorExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public String updateByPrimaryKeySelective(TryMybatisGenerator record) {
        SQL sql = new SQL();
        sql.UPDATE("try_mybatis_generator");
        
        if (record.getColumn1() != null) {
            sql.SET("column1 = #{column1,jdbcType=VARCHAR}");
        }
        
        if (record.getColumn2() != null) {
            sql.SET("column2 = #{column2,jdbcType=VARCHAR}");
        }
        
        if (record.getColumn3() != null) {
            sql.SET("column3 = #{column3,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table try_mybatis_generator
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    protected void applyWhere(SQL sql, TryMybatisGeneratorExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}