package com.example.demo.domain;

public class TryMybatisGenerator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column try_mybatis_generator.id
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column try_mybatis_generator.column1
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    private String column1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column try_mybatis_generator.column2
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    private String column2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column try_mybatis_generator.column3
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    private String column3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column try_mybatis_generator.id
     *
     * @return the value of try_mybatis_generator.id
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column try_mybatis_generator.id
     *
     * @param id the value for try_mybatis_generator.id
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column try_mybatis_generator.column1
     *
     * @return the value of try_mybatis_generator.column1
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column try_mybatis_generator.column1
     *
     * @param column1 the value for try_mybatis_generator.column1
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public void setColumn1(String column1) {
        this.column1 = column1 == null ? null : column1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column try_mybatis_generator.column2
     *
     * @return the value of try_mybatis_generator.column2
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column try_mybatis_generator.column2
     *
     * @param column2 the value for try_mybatis_generator.column2
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public void setColumn2(String column2) {
        this.column2 = column2 == null ? null : column2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column try_mybatis_generator.column3
     *
     * @return the value of try_mybatis_generator.column3
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column try_mybatis_generator.column3
     *
     * @param column3 the value for try_mybatis_generator.column3
     *
     * @mbg.generated Thu Apr 16 07:34:04 JST 2020
     */
    public void setColumn3(String column3) {
        this.column3 = column3 == null ? null : column3.trim();
    }
}